version: "3.7"

services:
  mongo:
    image: mongo:4.2.3
    container_name: database
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
    ports:
      - 27017:27017
